mainapp/urls.py
from . import views
from django.urls import path

app_name = "mainapp"
urlpatterns = [
    path("", views.home_view, name="home_view"),
    path("pl/", views.home_view_pl, name="home_view_pl"),
    path("new/", views.new_article_view, name="new_article"),
    path("<int:article_id>/", views.article_view, name="article_view"),
    path("<str:article_url>/", views.article_view_url, name="article_view_url"),
    path("edit/<int:article_id>/", views.edit_article_view, name="edit_article"),
    path("delete/<int:article_id>/", views.delete_article_view, name="delete_article"),
    path("access_denied/", views.access_denied_view, name="access_denied"),
]


myblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("mainapp.urls")),
    path("pl/", include("mainapp.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


mainapp/models.py
from django.db import models
from ckeditor.fields import RichTextField


class Article(models.Model):
    title = models.CharField(max_length=200)
    body = RichTextField(blank=True, null=True)
    publication_date = models.DateField()
    last_edit_date = models.DateField(null=True, blank=True)
    is_in_polish = models.BooleanField(default=False)
    article_image = models.ImageField(null=True, blank=True, upload_to="images/")
    url = models.SlugField(max_length=100, unique=True, null=True, blank=True)

    def __str__(self):
        return self.title


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    author = models.CharField(max_length=20)
    text = models.TextField()
    publication_date = models.DateTimeField()

    def ___str___(self):
        return self.text


mainapp/forms.py
from django import forms
from django.utils import timezone
from django.core.exceptions import ValidationError

import re
from .views import Article, Comment
from ckeditor.widgets import CKEditorWidget


class CreateArticle(forms.ModelForm):
    class Meta:
        model = Article
        fields = ["title", "body", "is_in_polish", "article_image", "url"]

    def __init__(self, *args, **kwargs):
        super(CreateArticle, self).__init__(*args, **kwargs)


class CreateComment(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["author", "text"]

    def __init__(self, request, *args, **kwargs):
        self.request = request
        initial_author = kwargs.pop("initial_author", None)
        super(CreateComment, self).__init__(*args, **kwargs)

        if initial_author is not None:
            self.fields["author"].initial = initial_author

    def clean_author(self):
        user = self.request.user
        author = self.cleaned_data["author"]
        if re.search(r"[()]+", author) and not user.is_superuser:
            raise ValidationError("Regular user cannot use this nickname")
        return author


mainapp/views.py
from django.shortcuts import (
    render,
    HttpResponse,
    HttpResponseRedirect,
    get_object_or_404,
    redirect,
)
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.decorators import user_passes_test

from .models import Article, Comment
from .forms import CreateArticle, CreateComment


def is_superuser(user):
    return user.is_superuser


def access_denied_view(response):
    return HttpResponse("Something went wrong :(")


def home_view(response):
    list_of_articles = Article.objects.filter(is_in_polish=False)[::-1]
    return render(response, "mainapp/base.html", {"list_of_articles": list_of_articles})


def home_view_pl(response):
    list_of_articles = Article.objects.filter(is_in_polish=True)[::-1]
    return render(
        response, "mainapp/basepl.html", {"list_of_articles": list_of_articles}
    )


def article_view(response, article_id):
    article = get_object_or_404(Article, pk=article_id)
    comments = Comment.objects.filter(article=article)
    admin_name = "ravdar (op)" if response.user.is_superuser else None
    if response.method == "POST":
        form = CreateComment(response, response.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.publication_date = timezone.now()
            comment.article = article
            comment = form.save()
            form = CreateComment(response, initial_author=admin_name)
    else:
        form = CreateComment(response, initial_author=admin_name)
    return render(
        response,
        "mainapp/displayarticle.html",
        {"article": article, "form": form, "comments": comments},
    )


def article_view_url(response, article_url):
    article = get_object_or_404(Article, url=article_url)
    comments = Comment.objects.filter(article=article)
    admin_name = "ravdar (op)" if response.user.is_superuser else None
    if response.method == "POST":
        form = CreateComment(response, response.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.publication_date = timezone.now()
            comment.article = article
            comment = form.save()
            form = CreateComment(response, initial_author=admin_name)
    else:
        form = CreateComment(response, initial_author=admin_name)
    if article.is_in_polish == True:
        return render(
            response,
            "mainapp/displayarticlepl.html",
            {"article": article, "form": form, "comments": comments},
        )
    else:
        return render(
            response,
            "mainapp/displayarticle.html",
            {"article": article, "form": form, "comments": comments},
        )


@user_passes_test(is_superuser, login_url="mainapp:access_denied")
def new_article_view(response):
    if response.method == "POST":
        form = CreateArticle(response.POST, response.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.publication_date = timezone.now()
            article = form.save()
            return HttpResponseRedirect(
                reverse("mainapp:article_view_url", args=(article.url,))
            )
    else:
        form = CreateArticle()
    return render(response, "mainapp/newarticle.html", {"form": form})


@user_passes_test(is_superuser, login_url="mainapp:access_denied")
def edit_article_view(response, article_id):
    article = get_object_or_404(Article, pk=article_id)

    if response.method == "POST":
        form = CreateArticle(response.POST, response.FILES, instance=article)
        if form.is_valid():
            article = form.save(commit=False)
            article.last_edit_date = timezone.now()
            article = form.save()

            return HttpResponseRedirect(
                reverse("mainapp:article_view", args=(article_id,))
            )
    else:
        form = CreateArticle(instance=article)

    return render(response, "mainapp/editarticle.html", {"form": form})


@user_passes_test(is_superuser, login_url="mainapp:access_denied")
def delete_article_view(response, article_id):
    article = get_object_or_404(Article, pk=article_id)
    article.delete()

    return redirect("mainapp:home_view")

mainapp/templates/mainapp/base.html
<html>
<style>
    body {
        margin: 0;
        padding: 0;
        font-family: -apple-system, BlinkMacSystemFont, sans-serif;
    }
</style>

<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<div id="logo">
    <img src="/media/images/crate_bar.png">
    {% if request.resolver_match.url_name == 'home_view_pl' or request.resolver_match.url_name == 'article_view_url' %}
    <a href="{% url 'mainapp:home_view_pl' %}"><img src="/media/images/logo.png" alt="logo"></a>
    {% else %}
    <a href="{% url 'mainapp:home_view' %}"><img src="/media/images/logo.png" alt="logo"></a>
    {% endif %}
</div>
{% if user.is_superuser %}
<a href="{% url 'mainapp:new_article' %}"><button type="button">New article</button></a>
{% endif %}
<div id="main-container">
    <div id="second-container">
        {% block content %}
        {% for article in list_of_articles %}
        {% if article.url != None %}
        {% if article.article_image %}
        <a href="{% url 'mainapp:article_view_url' article.url %}"><img src="{{article.article_image.url }}"
                id="article-image"></a>
        {% endif %}
        <p id="publication-date-label">{{article.publication_date}}</p>
        <h1 id="article-titles"><a href="{% url 'mainapp:article_view_url' article.url %}">{{article.title}}</a>
            {% else %}
            {% if article.article_image %}
            <a href="{% url 'mainapp:article_view_url' article.id %}"><img src="{{article.article_image.url }}"
                    id="article-image"></a>
            {% endif %}
            <p id="publication-date-label">{{article.publication_date}}</p>
            <h1 id="article-titles"><a href="{% url 'mainapp:article_view_url' article.id %}">{{article.title}}</a>
                {% endif %}
            </h1>
            {% endfor %}
            {% endblock %}
    </div>
</div>


</html>

mainapp/templates/mainapp/basepl.html
<html>
<style>
    body {
        margin: 0;
        padding: 0;
        font-family: -apple-system, BlinkMacSystemFont, sans-serif;
    }
</style>

<head>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'styles.css' %}">
</head>
<div id="logo">
    <img src="/media/images/crate_bar.png">
    <a href="{% url 'mainapp:home_view_pl' %}"><img src="/media/images/logo.png" alt="logo"></a>
</div>
{% if user.is_superuser %}
<a href="{% url 'mainapp:new_article' %}"><button type="button">Nowy artykuł</button></a>
{% endif %}
<div id="main-container">
    <div id="second-container">
        {% block content %}
        {% for article in list_of_articles %}
        {% if article.url != None %}
        {% if article.article_image %}
        <a href="{% url 'mainapp:article_view_url' article.url %}"><img src="{{article.article_image.url }}"
                id="article-image"></a>
        {% endif %}
        <p id="publication-date-label">{{article.publication_date}}</p>
        <h1 id="article-titles"><a href="{% url 'mainapp:article_view_url' article.url %}">{{article.title}}</a>
            {% else %}
            {% if article.article_image %}
            <a href="{% url 'mainapp:article_view_url' article.id %}"><img src="{{article.article_image.url }}"
                    id="article-image"></a>
            {% endif %}
            <p id="publication-date-label">{{article.publication_date}}</p>
            <h1 id="article-titles"><a href="{% url 'mainapp:article_view_url' article.id %}">{{article.title}}</a>
                {% endif %}
            </h1>
            {% endfor %}
            {% endblock %}
    </div>
</div>


</html>

mainapp/templates/mainapp/displayarticle.html
{% extends "mainapp/base.html" %}

{% block content %}
<div id="main-container">
    <div id="second-container">
        {% if article.article_image %}
        <img src="{{article.article_image.url }}" id="article-image">
        {% endif %}
        <p>Published: {{article.publication_date}}
            {% if article.last_edit_date != None %}
            Last edit: {{article.last_edit_date}}
            {% endif %}
        </p>
        <h1>{{article.title}}</h1>
        <p>{{article.body|safe}}</p>
        {% if user.is_superuser %}
        <a href="{%url 'mainapp:edit_article' article.id %}"><button type="button">Edit</button></a>
        <a href="{%url 'mainapp:delete_article' article.id %}"><button type="button">Delete</button></a>
        {% endif %}
    </div>
    <br>
    <br>
    <div id="second-container">
        <h3>Comments section</h3>
        {% for comment in comments %}
        <p> {{comment.publication_date}}
            {% if comment.author == "ravdar (op)" %}
            <span style="color: orangered; font-weight: bold;">{{ comment.author }}</span>
            {% else %}
            {{ comment.author }}
            {% endif %}
        <p>{{comment.text}}</p>
        {% endfor %}
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" , name="save">Submit</button>
        </form>
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/displayarticlepl.html
{% extends "mainapp/basepl.html" %}

{% block content %}
<div id="main-container">
    <div id="second-container">
        {% if article.article_image %}
        <img src="{{article.article_image.url }}" id="article-image">
        {% endif %}
        <p>Opublikowano: {{article.publication_date}}
            {% if article.last_edit_date != None %}
            Ostatnia edycja: {{article.last_edit_date}}
            {% endif %}
        </p>
        <h1>{{article.title}}</h1>
        <p>{{article.body|safe}}</p>
        {% if user.is_superuser %}
        <a href="{%url 'mainapp:edit_article' article.id %}"><button type="button">Edytuj</button></a>
        <a href="{%url 'mainapp:delete_article' article.id %}"><button type="button">Usuń</button></a>
        {% endif %}
    </div>
    <br>
    <br>
    <div id="second-container">
        <h3>Komentarze</h3>
        {% for comment in comments %}
        <p> {{comment.publication_date}}
            {% if comment.author == "ravdar (op)" %}
            <span style="color: orangered; font-weight: bold;">{{ comment.author }}</span>
            {% else %}
            {{ comment.author }}
            {% endif %}
        <p>{{comment.text}}</p>
        {% endfor %}
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" , name="save">Zatwierdź</button>
        </form>
    </div>
</div>
{% endblock %}

mainapp/templates/mainapp/editarticle.html
{% extends "mainapp/base.html" %}

{% block content %}
<h1>Edit article:</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {{form.as_p}}
    <button type="submit" name="update">Update</button>
</form>
{% endblock %}

mainapp/templates/mainapp/newarticle.html
{% extends "mainapp/base.html" %}

{% block content %}
<h1>Write new article:</h1>
<form method="post" action="/new/" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {{form.as_p}}
    <button type="submit" , name="save">Submit</button>
</form>
{% endblock %}